game_type: PD
vocab:
- 0
- 1
- 2
- 3
- "."
- ","
pad_index: 4
bos_index: 5
eos_index: 5
max_len: 3
# GFN params
emb_dim: 128
n_hid: 256
n_layers: 2
batch_size: 256
n_train_steps: 1000
is_detach_form_TB: 1
top_k_param_for_vis: 15 # In visualization of the emp_dist, how much top instance you want to visualize in the axis